version: "3"

env:
  GOOS: # windows or linux ?
    sh: go env GOOS
  VERSION: # program version
    sh: go run ./cli -version
  EXE: # executable extension (.exe or nothing)
    sh: 'if [ "$(go env GOOS)" = "windows" ]; then echo ".exe"; else echo ""; fi'
  BROWSER: # browser to open  page
    sh: 'if [ "$(go env GOOS)" = "windows" ]; then echo "Powershell Start-Process "; else echo "xdg-open"; fi'
  DATE: # date string
    sh: 'if [ "$(go env GOOS)" = "windows" ]; then echo "$(Powershell Get-Date -Format s)"; else echo "$(date -Iseconds)"; fi'

tasks:

  default:
    desc: default task will display task menu
    cmds:
      - task --list-all

  info: 
    desc: display various useful information
    deps: [build]
    cmds:
      - task --version
      - go version
      - bin/cli-{{.VERSION}}{{.EXE}} -info

  godoc: 
    desc: launch godoc viewer and open browser page on windows
    cmds:     
      - go install golang.org/x/tools/cmd/godoc@latest     
      - $( {{.BROWSER }} "http://localhost:6060" )
      - echo "Press Ctrl-c to exit the task" 
      - godoc -http :6060

  build:
    desc: build program and utilities
    deps: [generate]
    sources: # what triggers rebuild
      - ./**/*go
    cmds:
      - go mod tidy
      - go build -o bin/cli-{{.VERSION}}{{.EXE}} -ldflags "-X 'github.com/xavier268/goscrapper.BUILDDATE={{.DATE}}' -X 'github.com/xavier268/goscrapper.GITHASH=$(git rev-parse HEAD)'" ./cli

  test:
    desc: run all generator tests
    deps: [build]
    cmds:
      - go test ./parser # unit tests
      - go test -v -count=1 ./e2e # end-to-end tests

  clean: 
    desc: clean caches and binaries, and test dirs
    deps : # dependencies tasks will run in parallel
      - clean-linux
      - clean-windows

  clean-linux:
    internal: true
    platforms: [linux]
    ignore_error: true # ignore error if not found
    cmds:    
      - rm -rf autoscrapper/
      - rm -rf .task/
      - rm parser/y.output
      - rm -rf e2e/e2epack/

  clean-windows:
    internal: true
    platforms: [windows]
    ignore_error: true # ignore error if not found
    cmds:    
      - Powershell Remove-Item autoscrapper -Recurse
      - Powershell Remove-Item .task -Recurse 
      - Powershell Remove-Item parser/y.output
      - Powershell Remove-Item e2e/e2epack -Recurse

  generate:
    desc: generate all files
    sources: 
      - ./**/*.y   
    generates: # what triggers rebuild
      - ./**/y.output
      - ./**/parser.go
    cmds:
      - go generate ./...