# The major version should match with the application.
version : "0.1"

states: 
  - state : firstState 
    onstart : 
      - cond: cond1
        with: 
          what: ff
          where: gg
      - cond: cond2
        with: 
          what: ff
          where: gg

    next : secondState
    select : something

