// Code generated by goyacc -o parser.go grammar.y. DO NOT EDIT.

//line grammar.y:1

package parser

import __yyfmt__ "fmt"

//line grammar.y:3

// each object has a value and a type.
type value struct {
	v string // a string in go that produce the value of the object
	t string // a string representing the gotype of the object
	c int    // the code returned by lexer is stored here. Always set by the lexer, even for variables (set as IDENTIFIER). A valid go type, without spaces.
}

var lx *myLexer // shorthand for lx

//line grammar.y:37
type yySymType struct {
	yys    int
	value  value
	list   []string
	values []value
	mvalue map[string]value
}

const MULTI = 57346
const DIV = 57347
const MOD = 57348
const PLUS = 57349
const MINUS = 57350
const PLUSPLUS = 57351
const MINUSMINUS = 57352
const LTE = 57353
const GTE = 57354
const LT = 57355
const GT = 57356
const EQ = 57357
const NEQ = 57358
const COLON = 57359
const SEMICOLON = 57360
const DOT = 57361
const COMMA = 57362
const LBRACKET = 57363
const RBRACKET = 57364
const LPAREN = 57365
const RPAREN = 57366
const LBRACE = 57367
const RBRACE = 57368
const AND = 57369
const OR = 57370
const NOT = 57371
const DOTDOT = 57372
const ASSIGN = 57373
const QUESTION = 57374
const REGEXMATCH = 57375
const REGEXNOTMATCH = 57376
const LOWER = 57377
const UPPER = 57378
const FORMAT = 57379
const INTTYPE = 57380
const BOOLTYPE = 57381
const STRINGTYPE = 57382
const BINTYPE = 57383
const FOR = 57384
const RETURN = 57385
const WAITFOR = 57386
const OPTIONS = 57387
const IGNORE = 57388
const HEADLESS = 57389
const TIMEOUT = 57390
const DISTINCT = 57391
const FILTER = 57392
const CURRENT = 57393
const SORT = 57394
const LIMIT = 57395
const LET = 57396
const COLLECT = 57397
const ASC = 57398
const DESC = 57399
const NIL = 57400
const TRUE = 57401
const FALSE = 57402
const USE = 57403
const INTO = 57404
const KEEP = 57405
const WITH = 57406
const COUNT = 57407
const ALL = 57408
const ANY = 57409
const AGGREGATE = 57410
const EVENT = 57411
const LIKE = 57412
const IN = 57413
const WHILE = 57414
const BOOL = 57415
const AT = 57416
const IDENTIFIER = 57417
const IGNOREID = 57418
const STRING = 57419
const NUMBER = 57420
const NAMESPACESEPARATOR = 57421
const SELECT = 57422
const CLICK = 57423
const DOCUMENT = 57424
const PAGE = 57425
const CONTAINS = 57426

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"MULTI",
	"DIV",
	"MOD",
	"PLUS",
	"MINUS",
	"PLUSPLUS",
	"MINUSMINUS",
	"LTE",
	"GTE",
	"LT",
	"GT",
	"EQ",
	"NEQ",
	"COLON",
	"SEMICOLON",
	"DOT",
	"COMMA",
	"LBRACKET",
	"RBRACKET",
	"LPAREN",
	"RPAREN",
	"LBRACE",
	"RBRACE",
	"AND",
	"OR",
	"NOT",
	"DOTDOT",
	"ASSIGN",
	"QUESTION",
	"REGEXMATCH",
	"REGEXNOTMATCH",
	"LOWER",
	"UPPER",
	"FORMAT",
	"INTTYPE",
	"BOOLTYPE",
	"STRINGTYPE",
	"BINTYPE",
	"FOR",
	"RETURN",
	"WAITFOR",
	"OPTIONS",
	"IGNORE",
	"HEADLESS",
	"TIMEOUT",
	"DISTINCT",
	"FILTER",
	"CURRENT",
	"SORT",
	"LIMIT",
	"LET",
	"COLLECT",
	"ASC",
	"DESC",
	"NIL",
	"TRUE",
	"FALSE",
	"USE",
	"INTO",
	"KEEP",
	"WITH",
	"COUNT",
	"ALL",
	"ANY",
	"AGGREGATE",
	"EVENT",
	"LIKE",
	"IN",
	"WHILE",
	"BOOL",
	"AT",
	"IDENTIFIER",
	"IGNOREID",
	"STRING",
	"NUMBER",
	"NAMESPACESEPARATOR",
	"SELECT",
	"CLICK",
	"DOCUMENT",
	"PAGE",
	"CONTAINS",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line grammar.y:224

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 204

var yyAct = [...]int8{
	80, 48, 89, 88, 113, 79, 112, 93, 90, 84,
	46, 25, 20, 6, 85, 18, 13, 28, 45, 30,
	47, 33, 29, 32, 27, 35, 107, 96, 57, 55,
	105, 111, 106, 78, 62, 63, 64, 59, 61, 60,
	81, 68, 66, 67, 65, 69, 70, 96, 15, 95,
	117, 77, 109, 19, 17, 86, 16, 71, 72, 73,
	62, 63, 64, 59, 61, 60, 108, 68, 66, 67,
	65, 69, 70, 38, 103, 34, 92, 36, 37, 56,
	94, 91, 14, 71, 72, 73, 104, 97, 39, 40,
	41, 12, 102, 100, 76, 11, 75, 110, 101, 99,
	10, 33, 23, 32, 114, 35, 22, 3, 5, 44,
	116, 115, 8, 2, 74, 42, 43, 9, 118, 62,
	63, 64, 59, 61, 60, 21, 68, 66, 67, 65,
	69, 70, 26, 39, 40, 41, 1, 4, 82, 83,
	74, 7, 71, 72, 73, 87, 33, 53, 32, 98,
	35, 54, 24, 38, 44, 34, 31, 36, 37, 58,
	42, 43, 0, 0, 49, 51, 50, 52, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 38, 74,
	34, 0, 36, 37,
}

var yyPact = [...]int16{
	-1000, -1000, -61, -61, -27, -1000, -63, -27, -1000, -1000,
	-27, -1000, -1000, -64, -27, -7, 80, 80, -65, 80,
	126, -1000, -1000, -1000, 9, -1000, -1000, 80, 115, -1000,
	75, 0, 80, 80, 17, -66, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, 115, -57, 115, -1000, -1000,
	-1000, -1000, -1000, 126, -73, -67, -1000, 115, 80, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, 80, -68, 75, 56, 27,
	115, 125, 73, 72, 57, 80, 8, 6, -1000, 49,
	-1000, -1000, 30, -1000, -1000, -1000, 80, 7, -1000, -1000,
	-69, -1000, -71, 80, 115, -1000, -1000, -73, 126, -1000,
	115, -1000, 33, -1000, 115, -1000, -1000, 80, 115,
}

var yyPgo = [...]uint8{
	0, 0, 22, 19, 159, 156, 1, 152, 5, 145,
	3, 139, 138, 136, 113, 107, 137, 117, 108, 100,
	95, 91, 82, 79,
}

var yyR1 = [...]int8{
	0, 13, 13, 14, 16, 15, 15, 18, 6, 6,
	6, 6, 6, 6, 10, 9, 9, 17, 17, 19,
	19, 21, 21, 21, 20, 20, 23, 7, 7, 22,
	22, 4, 4, 4, 4, 4, 4, 4, 4, 4,
	4, 4, 4, 4, 4, 4, 4, 5, 5, 5,
	5, 5, 5, 1, 1, 2, 2, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 8,
	8, 12, 12, 11, 11,
}

var yyR2 = [...]int8{
	0, 4, 3, 0, 0, 2, 1, 3, 1, 1,
	1, 1, 3, 3, 3, 1, 3, 2, 1, 1,
	2, 3, 2, 2, 2, 3, 0, 1, 3, 4,
	2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 3, 1, 2, 3, 4, 3,
	3, 4, 3, 3, 3, 1, 1, 1, 1, 1,
	3, 3, 5, 1, 3,
}

var yyChk = [...]int16{
	-1000, -13, -14, -15, -16, -18, 74, -16, -18, -17,
	-19, -20, -21, 43, -22, 75, 83, 81, 42, 80,
	75, -17, -20, -21, -7, 75, -17, 31, -1, -2,
	-3, -5, 23, 21, 75, 25, 77, 78, 73, 8,
	9, 10, 35, 36, 29, -1, 75, -1, -6, 38,
	40, 39, 41, 21, 25, 20, -23, -1, -4, 7,
	9, 8, 4, 5, 6, 14, 12, 13, 11, 15,
	16, 27, 28, 29, 84, 21, 19, -3, -1, -8,
	-1, 23, -12, -11, 75, 71, -6, -9, -10, 75,
	75, -2, -1, 75, 24, 22, 20, -8, 24, 26,
	20, 26, 20, 17, -1, 22, 26, 20, 17, 22,
	-1, 24, 75, 75, -1, -10, -6, 17, -1,
}

var yyDef = [...]int8{
	3, -2, 4, 4, 0, 6, 0, 0, 5, 2,
	0, 18, 19, 0, 0, 0, 0, 0, 0, 0,
	0, 1, 17, 20, 24, 27, 26, 0, 22, 53,
	55, 0, 0, 0, 65, 0, 66, 67, 68, 47,
	48, 49, 50, 51, 52, 23, 0, 30, 7, 8,
	9, 10, 11, 0, 0, 0, 25, 21, 0, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 0, 0, 56, 0, 0,
	69, 0, 0, 0, 73, 0, 0, 0, 15, 0,
	28, 54, 0, 59, 57, 60, 0, 0, 62, 63,
	0, 64, 0, 0, 29, 12, 13, 0, 0, 58,
	70, 61, 0, 74, 71, 16, 14, 0, 72,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
	82, 83, 84,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:79
		{
			lx.finalize()
		}
	case 2:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:80
		{
			lx.finalize()
		}
	case 3:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:84
		{
			lx = yylex.(*myLexer)
		}
	case 4:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:88
		{
			lx.incOut()
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:98
		{
			lx.declInputParam(yyDollar[2].value.v, yyDollar[3].value.v)
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:105
		{
			yyVAL.value.v = "[]byte"
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:106
		{
			yyVAL.value.v = "[]" + yyDollar[2].value.v
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:111
		{ /* todo */
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:114
		{ /* todo */
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:115
		{ /* todo */
		}
	case 17:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:121
		{
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:122
		{
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:126
		{ /* todo */
		}
	case 20:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:127
		{ /* todo */
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:131
		{
			lx.vSetVar(yyDollar[1].value.v, yyDollar[3].value)
		}
	case 22:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:132
		{ /* todo */
		}
	case 23:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:133
		{ /* todo */
		}
	case 24:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:137
		{
			lx.declOutputParams(yyDollar[2].list)
			lx.saveOut()
		}
	case 25:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:138
		{ /* */
		}
	case 26:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:142
		{
			lx.addLines("}")
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:145
		{
			yyVAL.list = append(yyVAL.list, yyDollar[1].value.v)
		}
	case 28:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:146
		{
			yyVAL.list = append(yyDollar[1].list, yyDollar[3].value.v)
		}
	case 29:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:150
		{
			lx.forNameInExpression(yyDollar[2].value.v, yyDollar[4].value)
		}
	case 30:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:151
		{
			lx.selectExpression(yyDollar[2].value)
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:158
		{
			yyVAL.value = yyDollar[1].value
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:159
		{
			yyVAL.value = yyDollar[1].value
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:160
		{
			yyVAL.value = yyDollar[1].value
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:161
		{
			yyVAL.value = yyDollar[1].value
		}
	case 35:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:162
		{
			yyVAL.value = yyDollar[1].value
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:163
		{
			yyVAL.value = yyDollar[1].value
		}
	case 37:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:164
		{
			yyVAL.value = yyDollar[1].value
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:165
		{
			yyVAL.value = yyDollar[1].value
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:166
		{
			yyVAL.value = yyDollar[1].value
		}
	case 40:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:167
		{
			yyVAL.value = yyDollar[1].value
		}
	case 41:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:168
		{
			yyVAL.value = yyDollar[1].value
		}
	case 42:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:169
		{
			yyVAL.value = yyDollar[1].value
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:170
		{
			yyVAL.value = yyDollar[1].value
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:171
		{
			yyVAL.value = yyDollar[1].value
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:172
		{
			yyVAL.value = yyDollar[1].value
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:173
		{
			yyVAL.value = yyDollar[1].value
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:177
		{
			yyVAL.value = yyDollar[1].value
		}
	case 48:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:178
		{
			yyVAL.value = yyDollar[1].value
		}
	case 49:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:179
		{
			yyVAL.value = yyDollar[1].value
		}
	case 50:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:180
		{
			yyVAL.value = yyDollar[1].value
		}
	case 51:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:181
		{
			yyVAL.value = yyDollar[1].value
		}
	case 52:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:182
		{
			yyVAL.value = yyDollar[1].value
		}
	case 53:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:186
		{
			yyVAL.value = yyDollar[1].value
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:187
		{
			yyVAL.value = lx.vOpe2(yyDollar[2].value.c, yyDollar[1].value, yyDollar[3].value)
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:191
		{
			yyVAL.value = yyDollar[1].value
		}
	case 56:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:192
		{
			yyVAL.value = lx.vOpe1(yyDollar[1].value.c, yyDollar[2].value)
		}
	case 57:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:196
		{
			yyVAL.value = lx.vParen(yyDollar[2].value)
		}
	case 58:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:197
		{
			yyVAL.value = lx.vGetElementOf(yyDollar[1].value, yyDollar[3].value)
		}
	case 59:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:198
		{ /* todo - access an object key */
		}
	case 60:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:199
		{
			yyVAL.value = lx.vMakeArray(yyDollar[2].values)
		}
	case 61:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:200
		{ /* TODO - function call computing and returning a value */
		}
	case 62:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:201
		{ /* TODO - function call computing and returning a value - empty input params */
		}
	case 63:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:202
		{ /* constructs a litteral object - todo*/
		}
	case 64:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:203
		{ /* constructs a litteral object, where var names are used as key - todo*/
		}
	case 65:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:204
		{
			yyVAL.value = lx.vGetVar(yyDollar[1].value.v)
		}
	case 66:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:205
		{
			yyVAL.value = yyDollar[1].value
		}
	case 67:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:206
		{
			yyVAL.value = yyDollar[1].value
		}
	case 68:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:207
		{
			yyVAL.value = yyDollar[1].value
		}
	case 69:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:211
		{
			yyVAL.values = []value{yyDollar[1].value}
		}
	case 70:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:212
		{
			yyVAL.values = append(yyDollar[1].values, yyDollar[3].value)
		}
	case 71:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:216
		{ /* todo */
		}
	case 72:
		yyDollar = yyS[yypt-5 : yypt+1]
//line grammar.y:217
		{ /* todo */
		}
	case 73:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:221
		{ /* todo */
		}
	case 74:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:222
		{ /* todo */
		}
	}
	goto yystack /* stack new state and value */
}
