// Code generated by goyacc -o parser.go grammar.y. DO NOT EDIT.

//line grammar.y:1

    package parser
import __yyfmt__ "fmt"
//line grammar.y:3
		
    import (
        "fmt"
    )

    // keep the compiler happy
    _ = fmt.Println

    type keyword struct {
        v string
        t type
        c int // lexer/parser constant code
    } 

    var lx *myLexer // shorthand for lx

    type Doer [T any] interface {
        Eval[T]() (T, error)
    }


//line grammar.y:54
type yySymType struct {
	yys int            
    keyword keyword
}

const IDENTIFIER = 57346
const ASSIGN = 57347
const SEMICOLON = 57348
const CLICK = 57349
const INPUT = 57350
const IN = 57351
const PRINT = 57352
const SLOW = 57353
const LEFT = 57354
const RIGHT = 57355
const MIDDLE = 57356
const RETURN = 57357
const COMMA = 57358
const FOR = 57359
const SELECT = 57360
const AS = 57361
const FROM = 57362
const WHERE = 57363
const LIMIT = 57364
const LPAREN = 57365
const RPAREN = 57366
const LBRACKET = 57367
const RBRACKET = 57368
const LBRACE = 57369
const RBRACE = 57370
const DOT = 57371
const NUBMBER = 57372
const LEN = 57373
const NUMBER = 57374
const PLUS = 57375
const MINUS = 57376
const PLUSPLUS = 57377
const MINUSMINUS = 57378
const MULTI = 57379
const DIV = 57380
const MOD = 57381
const ABS = 57382
const BOOL = 57383
const NOT = 57384
const AND = 57385
const OR = 57386
const XOR = 57387
const EQ = 57388
const NEQ = 57389
const LT = 57390
const LTE = 57391
const GT = 57392
const GTE = 57393
const CONTAINS = 57394
const STRING = 57395
const FIND = 57396
const PATH = 57397
const WITH = 57398
const JOIN = 57399
const PAGE = 57400
const COLON = 57401
const TEXT = 57402
const ATTR = 57403
const OF = 57404
const DISTINCT = 57405
const AT = 57406
const RANGE = 57407

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENTIFIER",
	"ASSIGN",
	"SEMICOLON",
	"CLICK",
	"INPUT",
	"IN",
	"PRINT",
	"SLOW",
	"LEFT",
	"RIGHT",
	"MIDDLE",
	"RETURN",
	"COMMA",
	"FOR",
	"SELECT",
	"AS",
	"FROM",
	"WHERE",
	"LIMIT",
	"LPAREN",
	"RPAREN",
	"LBRACKET",
	"RBRACKET",
	"LBRACE",
	"RBRACE",
	"DOT",
	"NUBMBER",
	"LEN",
	"NUMBER",
	"PLUS",
	"MINUS",
	"PLUSPLUS",
	"MINUSMINUS",
	"MULTI",
	"DIV",
	"MOD",
	"ABS",
	"BOOL",
	"NOT",
	"AND",
	"OR",
	"XOR",
	"EQ",
	"NEQ",
	"LT",
	"LTE",
	"GT",
	"GTE",
	"CONTAINS",
	"STRING",
	"FIND",
	"PATH",
	"WITH",
	"JOIN",
	"PAGE",
	"COLON",
	"TEXT",
	"ATTR",
	"OF",
	"DISTINCT",
	"AT",
	"RANGE",
}

var yyStatenames = [...]string{
}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line grammar.y:272

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}


const yyPrivate = 57344

const yyLast = 240

var yyAct = [...]uint8{
	38, 128, 66, 53, 67, 40, 50, 39, 72, 107,
	122, 123, 129, 130, 21, 124, 55, 36, 37, 108,
	102, 80, 81, 30, 58, 59, 21, 80, 81, 98,
	78, 129, 130, 63, 80, 81, 69, 96, 68, 80,
	81, 97, 24, 76, 32, 61, 33, 95, 80, 81,
	48, 26, 43, 44, 45, 46, 80, 81, 106, 47,
	27, 49, 64, 100, 104, 101, 99, 80, 81, 20,
	105, 77, 25, 58, 103, 131, 3, 121, 76, 35,
	110, 109, 56, 31, 111, 34, 52, 112, 113, 57,
	80, 81, 68, 6, 54, 5, 60, 114, 17, 116,
	16, 65, 115, 117, 62, 118, 83, 84, 120, 119,
	85, 86, 87, 30, 29, 28, 22, 51, 42, 89,
	90, 93, 94, 91, 92, 125, 41, 82, 79, 132,
	133, 134, 24, 23, 32, 127, 33, 126, 88, 8,
	48, 26, 43, 44, 45, 46, 30, 18, 71, 47,
	27, 49, 70, 4, 73, 74, 75, 9, 2, 30,
	10, 11, 25, 12, 13, 24, 1, 32, 7, 33,
	14, 15, 0, 31, 26, 0, 0, 0, 24, 30,
	32, 0, 33, 27, 0, 0, 0, 26, 0, 0,
	0, 0, 0, 0, 0, 25, 27, 0, 24, 0,
	32, 0, 33, 0, 0, 0, 31, 26, 25, 0,
	0, 0, 0, 0, 0, 0, 27, 0, 19, 31,
	0, 0, 0, 0, 0, 0, 0, 0, 25, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 31,
}

var yyPact = [...]int16{
	-1000, -1000, 153, -1000, 153, -1000, -1000, 155, 153, 74,
	175, 175, 109, 80, 90, 109, -1000, -1000, 76, 175,
	8, -1000, -1000, -1000, 109, -1000, -1000, -1000, -1000, -1000,
	-1000, 92, 19, 34, -1000, 109, 142, 62, 24, 73,
	-1000, 109, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	12, -1000, -1000, 20, -1000, 47, -1000, 57, 175, -4,
	-1000, -1000, 48, -22, -1000, 42, -1000, -50, -1000, 13,
	75, 142, -1000, -1000, -1000, -1000, -1000, 175, -1000, 109,
	-1000, -1000, 109, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, 109, 88, 109, 90,
	-1000, -1000, -1000, -1000, 109, -1000, 88, 109, -1000, -1000,
	-1000, 71, 73, -1000, -16, -1000, 5, -5, -22, -1000,
	-22, -1000, -1000, -1000, 109, -9, 69, 10, -1000, 109,
	109, -1000, -1000, -22, -22,
}

var yyPgo = [...]uint8{
	0, 166, 158, 76, 153, 95, 93, 0, 6, 152,
	148, 8, 147, 69, 139, 3, 137, 135, 1, 133,
	4, 128, 7, 127, 5, 126, 118, 117, 116, 115,
	114, 104, 101, 2,
}

var yyR1 = [...]int8{
	0, 1, 2, 3, 3, 4, 4, 6, 6, 6,
	6, 6, 9, 9, 10, 10, 11, 11, 11, 11,
	5, 5, 5, 12, 12, 13, 13, 14, 14, 15,
	16, 16, 17, 17, 18, 18, 19, 19, 20, 7,
	7, 22, 22, 24, 24, 26, 26, 8, 8, 8,
	28, 28, 28, 28, 28, 27, 27, 29, 29, 31,
	31, 30, 30, 32, 32, 33, 25, 25, 25, 25,
	25, 25, 25, 23, 23, 23, 23, 23, 23, 23,
	23, 23, 23, 23, 23, 21, 21,
}

var yyR2 = [...]int8{
	0, 2, 0, 2, 1, 1, 2, 4, 4, 5,
	3, 2, 0, 1, 1, 2, 1, 1, 1, 1,
	3, 4, 2, 0, 1, 1, 3, 5, 8, 1,
	0, 1, 1, 2, 2, 2, 1, 2, 1, 3,
	1, 3, 1, 2, 1, 1, 1, 1, 1, 3,
	1, 1, 1, 1, 1, 4, 3, 2, 3, 1,
	3, 2, 3, 1, 3, 3, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1,
}

var yyChk = [...]int16{
	-1000, -1, -2, -3, -4, -5, -6, 15, -14, 4,
	7, 8, 10, 11, 17, 18, -5, -6, -12, 63,
	-13, -8, -28, -19, 23, 53, 32, 41, -29, -30,
	4, 64, 25, 27, -3, 5, -8, -8, -7, -22,
	-24, -25, -26, 33, 34, 35, 36, 40, 31, 42,
	-8, -27, 6, -15, 4, -7, 6, -13, 16, -7,
	4, 26, -31, -7, 28, -32, -33, -20, 4, -7,
	-9, -10, -11, 12, 13, 14, -8, 9, 6, -21,
	43, 44, -23, 33, 34, 37, 38, 39, 65, 46,
	47, 50, 51, 48, 49, -24, 25, 29, 9, 19,
	6, -8, 24, 26, 16, 28, 16, 59, 6, 6,
	-11, -8, -22, -24, -7, -20, -7, -15, -7, -33,
	-7, 6, 26, 6, 20, -7, -16, -17, -18, 21,
	22, 6, -18, -7, -7,
}

var yyDef = [...]int8{
	2, -2, 0, 1, 0, 4, 5, 23, 0, 0,
	0, 0, 0, 0, 0, 0, 3, 6, 0, 0,
	24, 25, 47, 48, 0, 50, 51, 52, 53, 54,
	36, 0, 0, 0, 22, 0, 12, 0, 0, 40,
	42, 0, 44, 66, 67, 68, 69, 70, 71, 72,
	45, 46, 11, 0, 29, 0, 20, 0, 0, 0,
	37, 57, 0, 59, 61, 0, 63, 0, 38, 0,
	0, 13, 14, 16, 17, 18, 19, 0, 10, 0,
	85, 86, 0, 73, 74, 75, 76, 77, 78, 79,
	80, 81, 82, 83, 84, 43, 0, 0, 0, 0,
	21, 26, 49, 58, 0, 62, 0, 0, 7, 8,
	15, 0, 39, 41, 0, 56, 0, 0, 60, 64,
	65, 9, 55, 27, 0, 30, 0, 31, 32, 0,
	0, 28, 33, 34, 35,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65,
}


var yyTok3 = [...]int8{
	0,
}


var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{
}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-2:yypt+1]
//line grammar.y:80
		{ /*todo*/ }
	case 2:
		yyDollar = yyS[yypt-0:yypt+1]
//line grammar.y:84
		{lx = yylex.(*myLexer)}
	case 3:
		yyDollar = yyS[yypt-2:yypt+1]
//line grammar.y:88
		{  }
	case 4:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:89
		{ }
	case 5:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:93
		{ /* todo */}
	case 6:
		yyDollar = yyS[yypt-2:yypt+1]
//line grammar.y:94
		{ /* todo */}
	case 7:
		yyDollar = yyS[yypt-4:yypt+1]
//line grammar.y:98
		{ /*todo*/}
	case 8:
		yyDollar = yyS[yypt-4:yypt+1]
//line grammar.y:99
		{ /*todo*/}
	case 9:
		yyDollar = yyS[yypt-5:yypt+1]
//line grammar.y:100
		{/*todo*/}
	case 10:
		yyDollar = yyS[yypt-3:yypt+1]
//line grammar.y:103
		{/*todo*/}
	case 11:
		yyDollar = yyS[yypt-2:yypt+1]
//line grammar.y:104
		{/*todo*/}
	case 12:
		yyDollar = yyS[yypt-0:yypt+1]
//line grammar.y:108
		{/*todo*/}
	case 13:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:109
		{/*todo*/}
	case 14:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:113
		{/*todo*/}
	case 15:
		yyDollar = yyS[yypt-2:yypt+1]
//line grammar.y:114
		{/*todo*/}
	case 16:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:118
		{/*todo*/}
	case 17:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:119
		{/*todo*/}
	case 18:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:120
		{/*todo*/}
	case 19:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:121
		{/*todo*/}
	case 20:
		yyDollar = yyS[yypt-3:yypt+1]
//line grammar.y:125
		{/*todo*/}
	case 21:
		yyDollar = yyS[yypt-4:yypt+1]
//line grammar.y:126
		{/*todo*/}
	case 22:
		yyDollar = yyS[yypt-2:yypt+1]
//line grammar.y:127
		{ /*todo*/ }
	case 23:
		yyDollar = yyS[yypt-0:yypt+1]
//line grammar.y:131
		{/*todo*/}
	case 24:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:132
		{/*todo*/}
	case 25:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:136
		{/*todo*/}
	case 26:
		yyDollar = yyS[yypt-3:yypt+1]
//line grammar.y:137
		{/*todo*/}
	case 27:
		yyDollar = yyS[yypt-5:yypt+1]
//line grammar.y:140
		{/*todo*/}
	case 28:
		yyDollar = yyS[yypt-8:yypt+1]
//line grammar.y:141
		{/*todo*/}
	case 29:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:145
		{/*todo*/}
	case 30:
		yyDollar = yyS[yypt-0:yypt+1]
//line grammar.y:149
		{/*todo*/}
	case 31:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:150
		{/*todo*/}
	case 32:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:154
		{/*todo*/}
	case 33:
		yyDollar = yyS[yypt-2:yypt+1]
//line grammar.y:155
		{/*todo*/}
	case 34:
		yyDollar = yyS[yypt-2:yypt+1]
//line grammar.y:159
		{/*todo*/}
	case 35:
		yyDollar = yyS[yypt-2:yypt+1]
//line grammar.y:160
		{/*todo*/}
	case 36:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:164
		{/*todo*/}
	case 37:
		yyDollar = yyS[yypt-2:yypt+1]
//line grammar.y:165
		{/*todo*/}
	case 38:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:169
		{/*todo*/}
	case 39:
		yyDollar = yyS[yypt-3:yypt+1]
//line grammar.y:178
		{/*todo*/}
	case 40:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:179
		{/*todo*/}
	case 43:
		yyDollar = yyS[yypt-2:yypt+1]
//line grammar.y:188
		{/*todo*/}
	case 44:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:189
		{/*todo*/}
	case 45:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:193
		{/*todo*/}
	case 46:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:194
		{/*todo*/}
	case 47:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:198
		{/*todo*/}
	case 48:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:199
		{/*todo*/}
	case 49:
		yyDollar = yyS[yypt-3:yypt+1]
//line grammar.y:200
		{/*todo*/}
	case 50:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:204
		{/*todo*/}
	case 51:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:205
		{/*todo*/}
	case 52:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:206
		{/*todo*/}
	case 53:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:207
		{/*todo*/}
	case 54:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:208
		{/*todo*/}
	case 55:
		yyDollar = yyS[yypt-4:yypt+1]
//line grammar.y:212
		{/*todo*/}
	case 56:
		yyDollar = yyS[yypt-3:yypt+1]
//line grammar.y:213
		{/*todo*/}
	case 57:
		yyDollar = yyS[yypt-2:yypt+1]
//line grammar.y:217
		{/*todo*/}
	case 58:
		yyDollar = yyS[yypt-3:yypt+1]
//line grammar.y:218
		{/*todo*/}
	case 59:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:222
		{/*todo*/}
	case 60:
		yyDollar = yyS[yypt-3:yypt+1]
//line grammar.y:223
		{/*todo*/}
	case 61:
		yyDollar = yyS[yypt-2:yypt+1]
//line grammar.y:227
		{/*todo*/}
	case 62:
		yyDollar = yyS[yypt-3:yypt+1]
//line grammar.y:228
		{/*todo*/}
	case 63:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:232
		{/*todo*/}
	case 64:
		yyDollar = yyS[yypt-3:yypt+1]
//line grammar.y:233
		{/*todo*/}
	case 65:
		yyDollar = yyS[yypt-3:yypt+1]
//line grammar.y:237
		{/*todo*/}
	case 66:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:241
		{/*todo*/}
	case 67:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:242
		{/*todo*/}
	case 68:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:243
		{/*todo*/}
	case 69:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:244
		{/*todo*/}
	case 70:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:245
		{/*todo*/}
	case 71:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:246
		{/*todo*/}
	case 72:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:247
		{/*todo*/}
	case 73:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:252
		{/*todo*/}
	case 74:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:253
		{/*todo*/}
	case 75:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:254
		{/*todo*/}
	case 76:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:255
		{/*todo*/}
	case 77:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:256
		{/*todo*/}
	case 78:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:257
		{/*todo*/}
	case 79:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:258
		{/*todo*/}
	case 80:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:259
		{/*todo*/}
	case 81:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:260
		{/*todo*/}
	case 82:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:261
		{/*todo*/}
	case 83:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:262
		{/*todo*/}
	case 84:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:263
		{/*todo*/}
	case 85:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:267
		{/*todo*/}
	case 86:
		yyDollar = yyS[yypt-1:yypt+1]
//line grammar.y:268
		{/*todo*/}
	}
	goto yystack /* stack new state and value */
}
