// Autogenerated file. DO NOT EDIT.
// Version: 0.2.1
// Date: n/a
// Built : n/a
// (c) Xavier Gandillot 2024

package e2epack
// Generated from C:\Users\xavie\Desktop\goscrapper\e2e\arith.sc


[31m ********* Error in arith :***************[0m


@a int
@b int

c = a+ [31m <<<<<<<<<<<<<<<<< syntax error [0m
b

RETURN
