// Autogenerated file. DO NOT EDIT.
// Version: 0.3.4
// Date: n/a
// Built : n/a
// (c) Xavier Gandillot 2024

package e2epack
// Generated from C:\Users\xavie\Desktop\goscrapper\e2e\call1.sc

import (
	"context"
)


type Input_call1_async struct {
	a int
	b int
	url string
}


type Output_call1_async struct {
	c int
}


// @ a int
// @ b int
// @ url string
// 
// c = a + b
// 
// RETURN c
func DoAsync_call1_async(_ctx context.Context,_ch chan<- Output_call1_async,  _in Input_call1_async) (_err error) {
var _out Output_call1_async
var a int = _in.a ; _ = a
var b int = _in.b ; _ = b
var url string = _in.url ; _ = url
// call to incOut
 _out = Output_call1_async{}
var c int= ((a) + (b));_=c
//call to saveOut
_out.c=c
select {case <- _ctx.Done():return _ctx.Err();case _ch <- _out:}
if _err = _ctx.Err() ; _err != nil { return _err}
// call to incOut
 _out = Output_call1_async{}
return _err
}
