// Autogenerated file. DO NOT EDIT.
// Version: 0.3.4
// Date: n/a
// Built : n/a
// (c) Xavier Gandillot 2024

package e2epack
// Generated from C:\Users\xavie\Desktop\goscrapper\e2e\call1.sc

import (
	"context"
)


type Input_call1 struct {
	a int
	b int
	url string
}


type Output_call1 struct {
	c int
}


// @ a int
// @ b int
// @ url string
// 
// c = a + b
// 
// RETURN c
func Do_call1(_ctx context.Context,_in Input_call1) (_out []Output_call1, _err error) {
var a int = _in.a ; _ = a
var b int = _in.b ; _ = b
var url string = _in.url ; _ = url
// call to incOut
 _out = append(_out, Output_call1{})
var c int= ((a) + (b));_=c
//call to saveOut
_out[len(_out)-1].c=c
if _err = _ctx.Err() ; _err != nil { return _out,_err}
// call to incOut
 _out = append(_out, Output_call1{})
return _out[:len(_out) -1], _err
}
