// Autogenerated file. DO NOT EDIT.
// Version: 0.3.2
// Date: n/a
// Built : n/a
// (c) Xavier Gandillot 2024

package e2epack
// Generated from C:\Users\xavie\Desktop\goscrapper\e2e\test9.sc

import (
	"github.com/xavier268/goscrapper/rt"
	"github.com/go-rod/rod"
)


type Input_test9 struct {
	url string
}


type Output_test9 struct {
	url string
}


// @url string
// p1 = PAGE url
// p2 = PAGE (url + "/login")
// RETURN url
func Do_test9(_in Input_test9) (_out []Output_test9, _err error) {
var url string = _in.url ; _ = url
// call to incOut
 _out = append(_out, Output_test9{})
var p1 *rod.Page= rt.GetPage( url );_=p1
var p2 *rod.Page= rt.GetPage(((( url ) + ("/login"))));_=p2
//call to saveOut
_out[len(_out)-1].url=url
// call to incOut
 _out = append(_out, Output_test9{})
return _out[:len(_out) -1], _err
}
