// Autogenerated file. DO NOT EDIT.
// Version: 0.3.2
// Date: n/a
// Built : n/a
// (c) Xavier Gandillot 2024

package e2epack
// Generated from C:\Users\xavie\Desktop\goscrapper\e2e\test4.sc

import (
	"github.com/go-rod/rod"
	"github.com/xavier268/goscrapper/rt"
)


type Input_test4 struct {
	a string
	b []string
}


type Output_test4 struct {
	c string
	a string
	d string
}


// @a string
// @b [string]
// 
// c = a  + a
// page = PAGE "google.com"
// SELECT FROM page ALL a AS z
//     d = a + a
//     RETURN c,a,d
func Do_test4(_in Input_test4) (_out []Output_test4, _err error) {
var a string = _in.a ; _ = a
var b []string = _in.b ; _ = b
// call to incOut
 _out = append(_out, Output_test4{})
var c string= (( a ) + ( a ));_=c
var page *rod.Page= rt.GetPage("google.com");_=page
{// select : parser.selopt{from:parser.value{v:" page ", t:"*rod.Page", c:0}, css:parser.value{v:" a ", t:"string", c:0}, loopv:"z", where:[]parser.value(nil), limit:parser.value{v:"", t:"", c:0}, cases:[]parser.casopt(nil)}
var d string= (( a ) + ( a ));_=d
//call to saveOut
_out[len(_out)-1].a=a
_out[len(_out)-1].c=c
_out[len(_out)-1].d=d
// call to incOut
 _out = append(_out, Output_test4{})
}
return _out[:len(_out) -1], _err
}
