// Autogenerated file. DO NOT EDIT.
// Version: 0.2.1
// Date: n/a
// Built : n/a
// (c) Xavier Gandillot 2024

package e2epack
// Generated from C:\Users\xavie\Desktop\goscrapper\e2e\testArith.sc

import (
)


type Input_testarith struct {
	a int
	b int
	a2 []int
	a1 [][]bool
}


type Output_testarith struct {
}


// 
// @a int
// @b int
// @a2 [int]
// @a1 [[bool]]
// 
// d = a+b-a*b/a
// 
// RETURN c
func Do_testarith(_in Input_testarith) (_res []Output_testarith, _err error) {
var a int = _in.a ; _ = a
var b int = _in.b ; _ = b
var a2 []int = _in.a2 ; _ = a2
var a1 [][]bool = _in.a1 ; _ = a1
var d int= (((((((( a ) + ( b ))) - ( a ))) * ( b ))) / ( a ));_=d
return _res, _err
}
