// Autogenerated file. DO NOT EDIT.
// Version: 0.2.0
// Date: n/a
// Built : n/a
// (c) Xavier Gandillot 2024

package e2epack
// Generated from C:\Users\xavie\Desktop\goscrapper\e2e\test1.sc

import (
	"github.com/xavier268/goscrapper/rt"
)




func Dotest1(toto int) () {
rt.Ignore("*.jpg","*.JPEG")
}

 