// Autogenerated file. DO NOT EDIT.
// Version: 0.2.1
// Date: n/a
// Built : n/a
// (c) Xavier Gandillot 2024

package e2epack
// Generated from C:\Users\xavie\Desktop\goscrapper\e2e\test6.sc

import (
)


type Input_test6 struct {
	i int
	ai []int
	aai [][]int
}


type Output_test6 struct {
	x1 int
	x2 int
}


// // testing arrays
// 
// @i int
// @ai [int]
// @aai [[int]]
// 
// 
// x1 = ai[i]
// x2 = ai[ 0]
// x3 = aai[1][2]
// x4 = aai[ai[3]][ai[ai[1]]]
// 
// RETURN x1,x2
func Do_test6(_in Input_test6) (_out []Output_test6, _err error) {
var i int = _in.i ; _ = i
var ai []int = _in.ai ; _ = ai
var aai [][]int = _in.aai ; _ = aai
// call to incOut
 _out = append(_out, Output_test6{})
{
var x1 int= ( ai )[ i ];_=x1
var x2 int= ( ai )[0];_=x2
var x3 int= (( aai )[1])[2];_=x3
var x4 int= (( aai )[( ai )[3]])[( ai )[( ai )[1]]];_=x4
//call to saveOut
_out[len(_out)-1].x1=x1
_out[len(_out)-1].x2=x2
// call to incOut
 _out = append(_out, Output_test6{})
}
return _out[:len(_out) -1], _err
}
